import fs from "node:fs";
import path from "node:path";
import YAML from "js-yaml";
import Parser from "rss-parser";
import { nanoid } from "nanoid";
import dayjs from "dayjs";
import { sb, insert, select, upsert } from "../lib/db.js";
import { summarizeAndTag, draftEmailReply, generateContentDerivatives } from "../lib/gpt.js";
import { sendMail } from "../lib/email.js";

function loadPlaybook(name){ try{ const file=path.join(process.env.PLAYBOOKS_DIR||"./playbooks",name+".yaml"); const raw=fs.readFileSync(file,"utf8"); return YAML.load(raw);} catch(e){ console.warn("Playbook missing:",name,e.message); return {} } }

async function harvestRSS(playbook){ if(!playbook?.feeds) return []; const parser=new Parser(); const results=[]; for(const feed of playbook.feeds){ try{ const f=await parser.parseURL(feed.url); for(const item of f.items.slice(0, feed.limit||5)){ const id=item.guid||item.id||nanoid(); const exists=await sb.from("documents").select("id").eq("ext_id",id); if(exists.data?.length) continue; const doc={ id:nanoid(), ext_id:id, source:feed.url, kind:"rss_item", title:item.title||"", author:item.creator||item.author||"", url:item.link||"", content:(item.contentSnippet||item.content||"").slice(0,10000), published_at:item.isoDate||item.pubDate||null }; await insert("documents",doc); results.push(doc);} } catch(e){ console.warn("RSS error",feed.url,e.message); } } return results; }

async function processRawEvents(playbook){ const { data: rows, error } = await sb.from("raw_events").select("*").order("received_at",{ascending:true}).limit(25); if(error) throw error; for(const evt of rows||[]){ try{ if(evt.kind==="email_inbound"){ const p=evt.payload||{}; const text=[p.Subject,p.FromFull?.Email,p.TextBody||p.HtmlBody].filter(Boolean).join("\n"); const parsed=await summarizeAndTag({ text, source:"email", playbook }); const doc={ id:nanoid(), ext_id:p.MessageID||evt.id, source:"email", kind:"email", title:p.Subject||"(no subject)", author:p.FromFull?.Email||p.From||"", url:"", content:(p.TextBody||p.HtmlBody||"").slice(0,15000), metadata:parsed, published_at:evt.received_at }; await insert("documents",doc);} await sb.from("raw_events").delete().eq("id",evt.id); } catch(e){ console.error("evt error",evt.id,e.message); } } }

async function qualifyLeads(playbook){ const { data: docs, error } = await sb.from("documents").select("*").order("created_at",{ascending:false}).limit(80); if(error) throw error; for(const d of docs||[]){ const { data: existing } = await sb.from("leads").select("id").eq("doc_id",d.id); if(existing?.length) continue; const meta=d.metadata||{}; if((meta.intent||"noise")!=="lead") continue; const rules=playbook?.scoring||[]; let score=Math.round((meta.confidence||0)*50); for(const r of rules){ const hit=(d.title+" "+d.content).toLowerCase().includes((r.match||"").toLowerCase()); if(hit) score += r.points||0; } const lead={ id:nanoid(), doc_id:d.id, score, status: score >= (playbook?.autorespond_threshold||75) ? "qualified" : "review", data: meta }; await insert("leads",lead); if(lead.status==="qualified" && playbook?.auto_reply){ const context={ sourceTitle:d.title, sourceAuthor:d.author, summary:meta.summary, tags:meta.tags, entities:meta.entities, score }; const template=fs.readFileSync("./templates/reply_lead.md","utf8"); const body=await draftEmailReply({ context, template }); await sendMail({ to: (playbook.auto_reply.to&&playbook.auto_reply.to[0]) || process.env.OWNER_EMAIL || "replace@client.com", subject: playbook.auto_reply.subject || "Let's build something exceptional", html: body }); await upsert("leads",{ id: lead.id, status: "replied" }); } } }

async function repurposeContent(playbook){ if(!playbook?.repurpose) return; const { data: docs } = await sb.from("documents").select("*").like("kind","rss_item").order("created_at",{ascending:false}).limit(10); for(const d of docs||[]){ const { data: done } = await sb.from("derivatives").select("id").eq("doc_id",d.id); if(done?.length) continue; const plan=await generateContentDerivatives({ artifact:d.content, channels: playbook.repurpose.channels||["linkedin","twitter"] }); await insert("derivatives",{ id:nanoid(), doc_id:d.id, payload: plan }); } }

export default async function handler(req,res){ try{ const leadPb=loadPlaybook("leads"); const contentPb=loadPlaybook("content"); await processRawEvents(leadPb); await harvestRSS(contentPb); await qualifyLeads(leadPb); await repurposeContent(contentPb); res.status(200).json({ ok:true, ts:new Date().toISOString() }); } catch(e){ console.error(e); res.status(500).json({ ok:false, error:e.message }); } }
